buildscript: scripts/build
postinstall: scripts/postinstall.sh
pip:
 - gunicorn
 - praekelt-python-gitmodel
dependencies:
 - nginx
 - postgresql-server-dev-all
 - libpq-dev
 - postgresql
 - redis-server
