language: python
python:
  - "2.7"
install:
  - ./install_libgit2
  - "pip install coveralls coverage --use-wheel"
  - "pip install -r requirements.pip --use-wheel"
script:
  - LIBGIT2=$VIRTUAL_ENV DJANGO_SETTINGS_MODULE=test_settings coverage run --source=cms manage.py test cms
after_success:
  - coveralls
