language: python
services:
  - elasticsearch
python:
  - "2.7"
install:
  - "pip install coveralls coverage --use-wheel"
  - "pip install git+http://github.com/universalcore/elastic-git.git#egg=elastic-git
  - "pip install -e . --use-wheel"
script:
  - ./run_tests.sh
after_success:
  - coveralls
