language: python
sudo: false
services:
  - elasticsearch
python:
  - "2.7"
install:
  - "pip install --upgrade pip"
  - "pip install coveralls coverage --use-wheel"
  - "pip install -e . --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
script:
  - curl -s download.elasticsearch.org/es2unix/es > $HOME/es
  - chmod +x $HOME/es
  - $HOME/es health -v
  - ./run_tests.sh
after_success:
  - coveralls
