language: python
python:
  - "2.7"
install:
  - ./utils/install_libgit2.sh
  - "pip install coveralls coverage --use-wheel"
  - "pip install -e . --use-wheel"
script:
  - ./run_tests.sh
after_success:
  - coveralls
